DROP TABLE IF EXISTS biopest;
CREATE TABLE IF NOT EXISTS biopest(
  bibnum VARCHAR(3)
, project VARCHAR(21)
, title VARCHAR(232)
, year INTEGER(4)
, keyword VARCHAR(1160)
, periodical VARCHAR(205)
, parent_title VARCHAR(138)
, author VARCHAR(575)
, citation VARCHAR(382)
, link VARCHAR(51)
);
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('001','Epoxide Hydrolase','A potent juvenile hormone mimic, 1-(4''-ethylphenoxy)-6,7-epoxy-3,7-dimethyl-2-octene, labeled with tritium in either the ethylphenyl- or geranyl-derived moiety',1972,'','J. Agric. Food Chem. (Journal of agricultural and food chemistry)','','Kamimura, H.; Hammock, B. D.; Yamamoto, I.; Casida, J. E.','Kamimura H, Hammock B, Yamamoto I, Casida J. (1972). J. Agric. Food Chem. 20:439–442','http://ucanr.org/sites/hammocklab/files/125095.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('001','Insect Biology','A potent juvenile hormone mimic, 1-(4''-ethylphenoxy)-6,7-epoxy-3,7-dimethyl-2-octene, labeled with tritium in either the ethylphenyl- or geranyl-derived moiety',1972,'','J. Agric. Food Chem. (Journal of agricultural and food chemistry)','','Kamimura, H.; Hammock, B. D.; Yamamoto, I.; Casida, J. E.','Kamimura H, Hammock B, Yamamoto I, Casida J. (1972). J. Agric. Food Chem. 20:439–442','http://ucanr.org/sites/hammocklab/files/125095.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('002','Epoxide Hydrolase','Preliminary chromatographic studies on the metabolites and photodecomposition products of the juvenoid 1-(4''-ethylphenoxy-6,7-epoxy-3,7- dimethyl-2-octene',1972,'','','Insect Juvenile Hormones: Chemistry and Action','Gill, S. S.; Hammock, B. D.; Yamamoto, I.; Casida, J. E.','Gill S, Hammock B, Yamamoto I, Casida  J. (1972). In: Insect Juvenile Hormones: Chemistry and Action (Academic Press, New York): 177–189','http://ucanr.org/sites/hammocklab/files/125138.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('002','Insect Biology','Preliminary chromatographic studies on the metabolites and photodecomposition products of the juvenoid 1-(4''-ethylphenoxy-6,7-epoxy-3,7- dimethyl-2-octene',1972,'','','Insect Juvenile Hormones: Chemistry and Action','Gill, S. S.; Hammock, B. D.; Yamamoto, I.; Casida, J. E.','Gill S, Hammock B, Yamamoto I, Casida  J. (1972). In: Insect Juvenile Hormones: Chemistry and Action (Academic Press, New York): 177–189','http://ucanr.org/sites/hammocklab/files/125138.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('003','Epoxide Hydrolase','Mammalian metabolism and environmental degradation of the juvenoid 1-(4''-ethylphenoxy)-3,7-dimethyl-6,7-epoxy-trans-2-octene and related compounds',1974,'Animals; Biodegradation, Environmental; Biotransformation; Carbon Radioisotopes; Chlorophyta/metabolism; Ethers, Cyclic/metabolism; Insecticides/metabolism; Juvenile Hormones/metabolism; Models, Chemical; Photochemistry; Plants; Terpenes/metabolism; Tritium','J. Agric. Food Chem. (Journal of agricultural and food chemistry)','','Gill, S. S.; Hammock, B. D.; Casida, J. E.','Gill S, Hammock B, Casida J. (1974). J. Agric. Food Chem. 22:386–395','http://ucanr.org/sites/hammocklab/files/125174.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('003','Insect Biology','Mammalian metabolism and environmental degradation of the juvenoid 1-(4''-ethylphenoxy)-3,7-dimethyl-6,7-epoxy-trans-2-octene and related compounds',1974,'Animals; Biodegradation, Environmental; Biotransformation; Carbon Radioisotopes; Chlorophyta/metabolism; Ethers, Cyclic/metabolism; Insecticides/metabolism; Juvenile Hormones/metabolism; Models, Chemical; Photochemistry; Plants; Terpenes/metabolism; Tritium','J. Agric. Food Chem. (Journal of agricultural and food chemistry)','','Gill, S. S.; Hammock, B. D.; Casida, J. E.','Gill S, Hammock B, Casida J. (1974). J. Agric. Food Chem. 22:386–395','http://ucanr.org/sites/hammocklab/files/125174.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('004','Epoxide Hydrolase','Synthesis and morphogenetic activity of derivatives and analogs of aryl geranyl ether juvenoids',1974,'','J. Agric. Food Chem. (Journal of agricultural and food chemistry)','','Hammock, B. D.; Gill, S. S.; Casida, J. E.','Hammock B, Gill S, Casida J. (1974). J. Agric. Food Chem. 22:379–385','http://ucanr.org/sites/hammocklab/files/125202.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('004','Insect Biology','Synthesis and morphogenetic activity of derivatives and analogs of aryl geranyl ether juvenoids',1974,'','J. Agric. Food Chem. (Journal of agricultural and food chemistry)','','Hammock, B. D.; Gill, S. S.; Casida, J. E.','Hammock B, Gill S, Casida J. (1974). J. Agric. Food Chem. 22:379–385','http://ucanr.org/sites/hammocklab/files/125202.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('005','Insect Biology','Insect metabolism of a phenyl epoxygeranyl ether juvenoid and related compounds',1974,'','Pestoc Biochem Physiol (Pesticide biochemistry and physiology)','','Hammock, B. D.; Gill, S. S.; Casida, J. E.','Hammock B, Gill S, Casida J. (1974). Pestoc Biochem Physiol 4:393–406','http://ucanr.org/sites/hammocklab/files/130986.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('006','Epoxide Hydrolase','Detection and analysis of epoxides with 4-(p-Nitrobenzyl)-pyridine',1974,'Chromatography, Paper; Chromatography, Thin Layer; Colorimetry; Epoxy Compounds/analysis; Ethers, Cyclic/analysis; Nitrobenzenes; Pyridines','Bull Environ Contam Toxicol (Bulletin of environmental contamination and toxicology)','','Hammock, L. G.; Hammock, B. D.; Casida, J. E.','Hammock L, Hammock B, Casida J. (1974). Bull Environ Contam Toxicol 12:759–764','http://ucanr.org/sites/hammocklab/files/125291.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('006','Insect Biology','Detection and analysis of epoxides with 4-(p-Nitrobenzyl)-pyridine',1974,'Chromatography, Paper; Chromatography, Thin Layer; Colorimetry; Epoxy Compounds/analysis; Ethers, Cyclic/analysis; Nitrobenzenes; Pyridines','Bull Environ Contam Toxicol (Bulletin of environmental contamination and toxicology)','','Hammock, L. G.; Hammock, B. D.; Casida, J. E.','Hammock L, Hammock B, Casida J. (1974). Bull Environ Contam Toxicol 12:759–764','http://ucanr.org/sites/hammocklab/files/125291.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('007','Epoxide Hydrolase','Metabolic O-dealkylation of 1-(4''-ethylphenoxy)-3,7-dimethyl-7-methoxy or ethoxy-trans-2-octene, potent juvenoids',1975,'','Pestoc Biochem Physiol (Pesticide biochemistry and physiology)','','Hammock, B. D.; Gill, S. S.; Hammock, L. G.; Casida, J. E.','Hammock B, Gill S, Hammock L, Casida J. (1975). Pestoc Biochem Physiol 5:12–18','http://ucanr.org/sites/hammocklab/files/125363.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('007','Insect Biology','Metabolic O-dealkylation of 1-(4''-ethylphenoxy)-3,7-dimethyl-7-methoxy or ethoxy-trans-2-octene, potent juvenoids',1975,'','Pestoc Biochem Physiol (Pesticide biochemistry and physiology)','','Hammock, B. D.; Gill, S. S.; Hammock, L. G.; Casida, J. E.','Hammock B, Gill S, Hammock L, Casida J. (1975). Pestoc Biochem Physiol 5:12–18','http://ucanr.org/sites/hammocklab/files/125363.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('008','Insect Biology','The influence of hemolymph-binding protein on juvenile hormone stability and distribution in Manduca sexta fat body and imaginal discs in vitro',1975,'Adipose Tissue/enzymology/metabolism; Animals; Drug Stability; Epoxide Hydrolases/metabolism; Esterases/metabolism; Hemolymph/physiology; Juvenile Hormones/metabolism; Kinetics; Larva; Lepidoptera/metabolism; Moths/metabolism; Protein Binding; Receptors, Cell Surface; Subcellular Fractions/enzymology; Wing/metabolism','Mol. Cell. Endocrinol. (Molecular and cellular endocrinology)','','Hammock, B.; Nowock, J.; Goodman, W.; Stamoudis, V.; Gilbert, L. I.','Hammock B, Nowock J, Goodman W, Stamoudis V, Gilbert L. (1975). Mol. Cell. Endocrinol. 3:167–184','http://ucanr.org/sites/hammocklab/files/131003.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('009','Insect Biology','NADPH dependent epoxidation of methyl farnesoate to juvenile hormone in the cockroach Blaberus giganteus L',1975,'Animals; Carbon Monoxide/pharmacology; Cockroaches; Depression, Chemical; Endocrine Glands/metabolism; Epoxy Compounds/biosynthesis; Fatty Acids, Unsaturated/metabolism; Female; Juvenile Hormones/biosynthesis; Methylene Blue/pharmacology; Microsomes/enzymology; NADH, NADPH Oxidoreductases/metabolism; Neurosecretory Systems/drug effects/enzymology/metabolism; Piperonyl Butoxide/pharmacology; Proadifen/pharmacology; Sesquiterpenes/metabolism; Solubility','Life Sci. (Life sciences)','','Hammock, B. D.','Hammock B. (1975). Life Sci. 17:323–328','http://ucanr.org/sites/hammocklab/files/131008.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('010','Epoxide Hydrolase','Soluble mammalian epoxide hydratase: action on juvenile hormone and other terpenoid epoxides',1976,'Animals; Cytosol/enzymology; Epoxide Hydrolases/metabolism; Hydro-Lyases/metabolism; Juvenile Hormones/metabolism; Kidney/enzymology; Kinetics; Liver/enzymology; Male; Mice; Microsomes/enzymology; Microsomes, Liver/enzymology','Comp. Biochem. Physiol., B (Comparative biochemistry and physiology. B, Comparative biochemistry)','','Hammock, B. D.; Gill, S. S.; Stamoudis, V.; Gilbert, L. I.','Hammock B, Gill S, Stamoudis V, Gilbert L. (1976). Comp. Biochem. Physiol., B 53:263–265','http://ucanr.org/sites/hammocklab/files/125096.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('010','Insect Biology','Soluble mammalian epoxide hydratase: action on juvenile hormone and other terpenoid epoxides',1976,'Animals; Cytosol/enzymology; Epoxide Hydrolases/metabolism; Hydro-Lyases/metabolism; Juvenile Hormones/metabolism; Kidney/enzymology; Kinetics; Liver/enzymology; Male; Mice; Microsomes/enzymology; Microsomes, Liver/enzymology','Comp. Biochem. Physiol., B (Comparative biochemistry and physiology. B, Comparative biochemistry)','','Hammock, B. D.; Gill, S. S.; Stamoudis, V.; Gilbert, L. I.','Hammock B, Gill S, Stamoudis V, Gilbert L. (1976). Comp. Biochem. Physiol., B 53:263–265','http://ucanr.org/sites/hammocklab/files/125096.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('011','Epoxide Hydrolase','The degradative metabolism of juvenoids by insects',1976,'','','The Juvenile Hormones','Hammock, B. D.; Quistad, G. B.','Hammock B, Quistad G. (1976). In: The Juvenile Hormones (Plenum Press, New York): 374–393','http://ucanr.org/sites/hammocklab/files/125101.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('011','Esterase and Amidase','The degradative metabolism of juvenoids by insects',1976,'','','The Juvenile Hormones','Hammock, B. D.; Quistad, G. B.','Hammock B, Quistad G. (1976). In: The Juvenile Hormones (Plenum Press, New York): 374–393','http://ucanr.org/sites/hammocklab/files/125101.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('011','Insect Biology','The degradative metabolism of juvenoids by insects',1976,'','','The Juvenile Hormones','Hammock, B. D.; Quistad, G. B.','Hammock B, Quistad G. (1976). In: The Juvenile Hormones (Plenum Press, New York): 374–393','http://ucanr.org/sites/hammocklab/files/125101.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('012','Insect Biology','The binding protein as a modulator of juvenile hormone stability and uptake',1976,'','','The Juvenile Hormones','Nowock, J.; Hammock, B. D.; Gilbert, L. I.','Nowock  J, Hammock  B, Gilbert  L. (1976). In: The Juvenile Hormones (Plenum Press, New York): 354–373','http://ucanr.org/sites/hammocklab/files/130844.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('013','Insect Biology','Mechanisms of resistance to the juvenoid methoprene in the house fly Musca domestica L',1977,'','Pestoc Biochem Physiol (Pesticide biochemistry and physiology)','','Hammock, B. D.; Mumby, S. M.; Lee, P. W.','Hammock B, Mumby S, Lee P. (1977). Pestoc Biochem Physiol 7:261–272','http://ucanr.org/sites/hammocklab/files/130849.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('014','Esterase and Amidase','Selective inhibition of JH esterases from cockroach hemolymph',1977,'','Pestoc Biochem Physiol (Pesticide biochemistry and physiology)','','Hammock, B. D.; Sparks, T. C.; Mumby, S. M.','Hammock B, Sparks T, Mumby S. (1977). Pestoc Biochem Physiol 7:517–530','http://ucanr.org/sites/hammocklab/files/125842.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('014','Immunoassay','Selective inhibition of JH esterases from cockroach hemolymph',1977,'','Pestoc Biochem Physiol (Pesticide biochemistry and physiology)','','Hammock, B. D.; Sparks, T. C.; Mumby, S. M.','Hammock B, Sparks T, Mumby S. (1977). Pestoc Biochem Physiol 7:517–530','http://ucanr.org/sites/hammocklab/files/125842.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('014','Insect Biology','Selective inhibition of JH esterases from cockroach hemolymph',1977,'','Pestoc Biochem Physiol (Pesticide biochemistry and physiology)','','Hammock, B. D.; Sparks, T. C.; Mumby, S. M.','Hammock B, Sparks T, Mumby S. (1977). Pestoc Biochem Physiol 7:517–530','http://ucanr.org/sites/hammocklab/files/125842.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('015','Epoxide Hydrolase','Acute toxicity and developmental effects of analogues of ethyl α-(4-chlorophenoxy)-α-methylpropionate on two insects, Oncopeltus fasciatus and Tenebrio molitor',1978,'','J. Agric. Food Chem. (Journal of agricultural and food chemistry)','','Hammock, B. D.; Kuwano, E.; Ketterman, A.; Scheffrahn, R. H.; Thompson, S. N.; Sallume, D.','Hammock B, Kuwano E, Ketterman A, Scheffrahn R, Thompson S, Sallume D. (1978). J. Agric. Food Chem. 26:166–170','http://ucanr.org/sites/hammocklab/files/125123.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('015','Immunoassay','Acute toxicity and developmental effects of analogues of ethyl α-(4-chlorophenoxy)-α-methylpropionate on two insects, Oncopeltus fasciatus and Tenebrio molitor',1978,'','J. Agric. Food Chem. (Journal of agricultural and food chemistry)','','Hammock, B. D.; Kuwano, E.; Ketterman, A.; Scheffrahn, R. H.; Thompson, S. N.; Sallume, D.','Hammock B, Kuwano E, Ketterman A, Scheffrahn R, Thompson S, Sallume D. (1978). J. Agric. Food Chem. 26:166–170','http://ucanr.org/sites/hammocklab/files/125123.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('015','Insect Biology','Acute toxicity and developmental effects of analogues of ethyl α-(4-chlorophenoxy)-α-methylpropionate on two insects, Oncopeltus fasciatus and Tenebrio molitor',1978,'','J. Agric. Food Chem. (Journal of agricultural and food chemistry)','','Hammock, B. D.; Kuwano, E.; Ketterman, A.; Scheffrahn, R. H.; Thompson, S. N.; Sallume, D.','Hammock B, Kuwano E, Ketterman A, Scheffrahn R, Thompson S, Sallume D. (1978). J. Agric. Food Chem. 26:166–170','http://ucanr.org/sites/hammocklab/files/125123.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('016','Immunoassay','A rapid assay for insect juvenile hormone esterase activity',1977,'','Anal. Biochem. (Analytical biochemistry)','','Hammock, B. D.; Sparks, T. C.','Hammock B, Sparks T. (1977). Anal. Biochem. 82:573–579','http://ucanr.org/sites/hammocklab/files/130861.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('016','Insect Biology','A rapid assay for insect juvenile hormone esterase activity',1977,'','Anal. Biochem. (Analytical biochemistry)','','Hammock, B. D.; Sparks, T. C.','Hammock B, Sparks T. (1977). Anal. Biochem. 82:573–579','http://ucanr.org/sites/hammocklab/files/130861.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('017','Immunoassay','Inhibition of epoxidation of methyl farnesoate to juvenile hormone III by cockroach corpus allatum homogenates',1978,'','Pestoc Biochem Physiol (Pesticide biochemistry and physiology)','','Hammock, B. D.; Mumby, S. M.','Hammock B, Mumby S. (1978). Pestoc Biochem Physiol 9:39–47','http://ucanr.org/sites/hammocklab/files/130865.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('017','Insect Biology','Inhibition of epoxidation of methyl farnesoate to juvenile hormone III by cockroach corpus allatum homogenates',1978,'','Pestoc Biochem Physiol (Pesticide biochemistry and physiology)','','Hammock, B. D.; Mumby, S. M.','Hammock B, Mumby S. (1978). Pestoc Biochem Physiol 9:39–47','http://ucanr.org/sites/hammocklab/files/130865.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('018','Immunoassay','Development of an S-bioallethrin specific antibody',1978,'Allethrin/analogs & derivatives/immunology; Animals; Antibody Formation; Antibody Specificity; Binding Sites, Antibody; Cattle; Immunodiffusion; Pesticide Residues; Rabbits','J. Agric. Food Chem. (Journal of agricultural and food chemistry)','','Wing, K. D.; Hammock, B. D.; Wustner, D. A.','Wing K, Hammock B, Wustner D. (1978). J. Agric. Food Chem. 26:1328–1333','http://ucanr.org/sites/hammocklab/files/126294.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('019','Insect Biology','Haemolymph juvenile hormone esterase activity in synchronous last instar larvae of the cabbage looper, Trichoplusia ni',1979,'','J. Insect Physiol. (Journal of insect physiology)','','Sparks, T. C.; Willis, W. S.; Shorey, H. H.; Hammock, B. D.','Sparks T, Willis W, Shorey H, Hammock B. (1979). J. Insect Physiol. 25:125–132','http://ucanr.org/sites/hammocklab/files/130876.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('020','Insect Biology','Chromatographic fractionation of aggregation and sex pheromones of Nippostrongylus brasiliensis (Nematoda)',1979,'','J. Exp. Zool. (The Journal of experimental zoology)','','Bone, L. W.; Gaston, L. K.; Hammock, B. D.; Shorey, H. H.','Bone L, Gaston L, Hammock B, Shorey H. (1979). J. Exp. Zool. 208:311–318','http://ucanr.org/sites/hammocklab/files/130884.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('021','Epoxide Hydrolase','A partition assay for epoxide hydrases acting on insect juvenile hormone and an epoxide-containing juvenoid',1979,'Animals; Epoxide Hydrolases/analysis; Insect Hormones; Insects; Juvenile Hormones; Solubility; Solvents','Anal. Biochem. (Analytical biochemistry)','','Mumby, S. M.; Hammock, B. D.','Mumby S, Hammock B. (1979). Anal. Biochem. 92:16–21','http://ucanr.org/sites/hammocklab/files/125143.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('021','Insect Biology','A partition assay for epoxide hydrases acting on insect juvenile hormone and an epoxide-containing juvenoid',1979,'Animals; Epoxide Hydrolases/analysis; Insect Hormones; Insects; Juvenile Hormones; Solubility; Solvents','Anal. Biochem. (Analytical biochemistry)','','Mumby, S. M.; Hammock, B. D.','Mumby S, Hammock B. (1979). Anal. Biochem. 92:16–21','http://ucanr.org/sites/hammocklab/files/125143.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('022','Esterase and Amidase','Synthesis and bioassay of carbamate inhibitors of the juvenile hormone hydrolyzing esterases from the housefly, Musca domestica',1979,'','J. Agric. Food Chem. (Journal of agricultural and food chemistry)','','Mumby, S. M.; Hammock, B. D.; Sparks, T. C.; Ota, K.','Mumby S, Hammock B, Sparks T, Ota K. (1979). J. Agric. Food Chem. 27:763–765','http://ucanr.org/sites/hammocklab/files/125854.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('022','Insect Biology','Synthesis and bioassay of carbamate inhibitors of the juvenile hormone hydrolyzing esterases from the housefly, Musca domestica',1979,'','J. Agric. Food Chem. (Journal of agricultural and food chemistry)','','Mumby, S. M.; Hammock, B. D.; Sparks, T. C.; Ota, K.','Mumby S, Hammock B, Sparks T, Ota K. (1979). J. Agric. Food Chem. 27:763–765','http://ucanr.org/sites/hammocklab/files/125854.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('023','Insect Biology','The possible role of carnitine in the selective toxicity of the miticide cycloprate',1979,'','Pestoc Biochem Physiol (Pesticide biochemistry and physiology)','','Quistad, G. B.; Staiger, L. E.; Schooley, D. A.; Sparks, T. C.; Hammock, B. D.','Quistad G, Staiger L, Schooley D, Sparks T, Hammock B. (1979). Pestoc Biochem Physiol 11:159–165','http://ucanr.org/sites/hammocklab/files/130901.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('024','Epoxide Hydrolase','Substrate selectivity and stereochemistry of enzymatic epoxide hydration in the soluble fraction of mouse liver',1979,'','Pestoc Biochem Physiol (Pesticide biochemistry and physiology)','','Mumby, S. M.; Hammock, B. D.','Mumby S, Hammock B. (1979). Pestoc Biochem Physiol 11:275–284','http://ucanr.org/sites/hammocklab/files/125154.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('025','Insect Biology','Effects of the anti hormone-hormone mimic ETB on the induction of insect juvenile hormone esterase in Trichoplusia ni',1979,'Animals; Dose-Response Relationship, Drug; Enzyme Induction/drug effects; Esterases/biosynthesis; Hydroxybenzoates/administration & dosage/pharmacology; Insects; Juvenile Hormones/antagonists & inhibitors/metabolism; Receptors, Cell Surface/drug effects','Life Sci. (Life sciences)','','Sparks, T. C.; Wing, K. D.; Hammock, B. D.','Sparks T, Wing K, Hammock B. (1979). Life Sci. 25:445–450','http://ucanr.org/sites/hammocklab/files/130909.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('026','Epoxide Hydrolase','Hydration of cis- and trans-epoxymethyl stearates by the cytosolic epoxide hydrase of mouse liver',1979,'Animals; Cytosol/enzymology; Epoxide Hydrolases/metabolism; Epoxy Compounds; Isomerism; Liver/enzymology; Male; Mice; Stearates; Stearic Acids; Subcellular Fractions/enzymology; Substrate Specificity','Biochem. Biophys. Res. Commun. (Biochemical and biophysical research communications)','','Gill, S. S.; Hammock, B. D.','Gill S, Hammock B. (1979). Biochem. Biophys. Res. Commun. 89:965–971','http://ucanr.org/sites/hammocklab/files/125162.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('027','Insect Biology','A comparison of the induced and naturally occurring juvenile hormone esterases from last instar larvae of Trichoplusia ni',1979,'','Insect Biochem. (Insect biochemistry)','','Sparks, T. C.; Hammock, B. D.','Sparks T, Hammock B. (1979). Insect Biochem. 9:411–421','http://ucanr.org/sites/hammocklab/files/130916.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('028','Epoxide Hydrolase','Stability of epoxide-containing juvenoids to dilute aqueous acid',1979,'','J Agric Food Chem (Journal of agricultural and food chemistry)','','Mumby, S. M.; Hammock, B. D.','Mumby S, Hammock B. (1979). J Agric Food Chem 27:1223–1228','http://ucanr.org/sites/hammocklab/files/125170.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('028','Insect Biology','Stability of epoxide-containing juvenoids to dilute aqueous acid',1979,'','J Agric Food Chem (Journal of agricultural and food chemistry)','','Mumby, S. M.; Hammock, B. D.','Mumby S, Hammock B. (1979). J Agric Food Chem 27:1223–1228','http://ucanr.org/sites/hammocklab/files/125170.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('029','Insect Biology','Induction and regulation of juvenile hormone esterases during the last larval instar of the cabbage looper, Trichoplusia ni',1979,'','J. Insect Physiol. (Journal of insect physiology)','','Sparks, T. C.; Hammock, B. D.','Sparks T, Hammock B. (1979). J. Insect Physiol. 25:551–560','http://ucanr.org/sites/hammocklab/files/130924.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('030','Immunoassay','Stereoselectivity of a radioimmunoassay for the insecticide S-bioallethrin',1979,'Binding, Competitive; Insecticides; Isomerism; Radioimmunoassay/methods; Structure-Activity Relationship','Experientia (Experientia)','','Wing, K. D.; Hammock, B. D.','Wing K, Hammock B. (1979). Experientia 35:1619–1620','http://ucanr.org/sites/hammocklab/files/126337.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('031','Epoxide Hydrolase','Comparison of epoxide hydrases in the soluble and microsomal fractions of mammalian liver',1980,'','','Molecular Basis of Environmental Toxicity','Hammock, B. D.; Gill, S. S.; Mumby, S. M.; Ota, K.','Hammock B, Gill S, Mumby S, Ota  K. (1980). In: Molecular Basis of Environmental Toxicity (Ann Arbor Science Publishers, Ann Arbor, Michigan): 229–272','http://ucanr.org/sites/hammocklab/files/125175.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('032','Epoxide Hydrolase','Distribution and properties of a mammalian soluble epoxide hydrase',1980,'Aging; Animals; Chromatography, Gel; Epoxide Hydrolases/metabolism; Kinetics; Liver/enzymology; Male; Mice; Molecular Weight; Rabbits; Rats; Sex Factors; Solubility; Species Specificity; Subcellular Fractions/enzymology','Biochem. Pharmacol. (Biochemical pharmacology)','','Gill, S. S.; Hammock, B. D.','Gill S, Hammock B. (1980). Biochem. Pharmacol. 29:389–395','http://ucanr.org/sites/hammocklab/files/125177.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('033','Epoxide Hydrolase','Cytosolic and microsomal epoxide hydrolases: differential properties in mammalian liver',1980,'Allyl Compounds; Animals; Benzene; Cytosol/enzymology; Epoxide Hydrolases/metabolism; Guinea Pigs; Hydrogen-Ion Concentration; Liver/enzymology/ultrastructure; Mice; Microsomes, Liver/enzymology; Rats; Styrenes; Substrate Specificity','Science (Science)','','Ota, K.; Hammock, B. D.','Ota K, Hammock B. (1980). Science 207:1479–1481','http://ucanr.org/sites/hammocklab/files/125181.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('034','Epoxide Hydrolase','Extramicrosomal epoxide hydration',1980,'','','Microsomes, Drug Oxidations, and Chemical Carcinogenesis','Hammock, B. D.; El-Tantawy, M.; Gill, S. S.; Hasegawa, L.; Mullin, C. A.; Ota, K.','Hammock B, El-Tantawy M, Gill S, Hasegawa  L, Mullin  C, Ota  K. (1980). In: Microsomes, Drug Oxidations, and Chemical Carcinogenesis (Academic Press, New York): 655–658','http://ucanr.org/sites/hammocklab/files/125183.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('035','Epoxide Hydrolase','The effect of hepatic microsomal and cytosolic subcellular fractions on the mutagenic activity of epoxide-containing compounds in the Salmonella assay',1980,'Animals; Biotransformation; Cytosol/enzymology; Epoxide Hydrolases/metabolism; Epoxy Compounds/pharmacology; Ethers, Cyclic/pharmacology; Guinea Pigs; Liver/enzymology; Mice; Microsomes, Liver/enzymology; Mutagenicity Tests; Mutagens; Rats; Salmonella typhimurium/genetics','Mutat. Res. (Mutation research)','','El-Tantawy, M. A.; Hammock, B. D.','El-Tantawy M, Hammock B. (1980). Mutat. Res. 79:59–71','http://ucanr.org/sites/hammocklab/files/125187.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('036','Epoxide Hydrolase','A rapid radiometric assay for mammalian cytosolic epoxide hydrolase',1980,'Animals; Cytosol/enzymology; Epoxide Hydrolases/analysis/antagonists & inhibitors; Glutathione/pharmacology; Glutathione Transferase/metabolism; Guinea Pigs; Isotope Labeling; Kinetics; Liver/enzymology; Male; Mice; Microsomes, Liver/enzymology; Rats; Styrenes/metabolism','Anal. Biochem. (Analytical biochemistry)','','Mullin, C. A.; Hammock, B. D.','Mullin C, Hammock B. (1980). Anal. Biochem. 106:476–485','http://ucanr.org/sites/hammocklab/files/125188.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('037','Epoxide Hydrolase','Mutagenicity of psoralen epoxides',1980,'Animals; Epoxy Compounds/pharmacology; Mice; Mutagenicity Tests; Mutagens; Psoralens/pharmacology; Rats; Salmonella typhimurium/genetics','Mutat. Res. (Mutation research)','','Ivie, G. W.; Macgregor, J. T.; Hammock, B. D.','Ivie G, Macgregor J, Hammock B. (1980). Mutat. Res. 79:73–77','http://ucanr.org/sites/hammocklab/files/125193.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('038','Immunoassay','Potential of immunochemical technology for pesticide analysis',1980,'','','Pesticide Analytical Methodology','Hammock, B. D.; Mumma, R. O.','Hammock B, Mumma R. (1980). In: Pesticide Analytical Methodology (ACS Publications, Washington, DC): 321–352','http://ucanr.org/sites/hammocklab/files/126369.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('039','Epoxide Hydrolase','Hydration of an 18O epoxide by a cytosolic epoxide hydrolase from mouse liver',1980,'Animals; Cytosol/enzymology; Epoxide Hydrolases/metabolism; Epoxy Compounds/metabolism; Ethers, Cyclic/metabolism; Liver/enzymology; Male; Mice; Oxygen Isotopes/diagnostic use','Life Sci. (Life sciences)','','Hammock, B. D.; Ratcliff, M.; Schooley, D. A.','Hammock B, Ratcliff M, Schooley D. (1980). Life Sci. 27:1635–1641','http://ucanr.org/sites/hammocklab/files/125193.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('039','Insect Biology','Hydration of an 18O epoxide by a cytosolic epoxide hydrolase from mouse liver',1980,'Animals; Cytosol/enzymology; Epoxide Hydrolases/metabolism; Epoxy Compounds/metabolism; Ethers, Cyclic/metabolism; Liver/enzymology; Male; Mice; Oxygen Isotopes/diagnostic use','Life Sci. (Life sciences)','','Hammock, B. D.; Ratcliff, M.; Schooley, D. A.','Hammock B, Ratcliff M, Schooley D. (1980). Life Sci. 27:1635–1641','http://ucanr.org/sites/hammocklab/files/125193.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('040','Insect Biology','Partial purification of the aggregation pheromone nippolure from female Nippostrongylus brasiliensis (Nematoda)',1980,'','J. Chem. Ecol. (Journal of chemical ecology)','','Bone, L. W.; Hammock, B. D.; Gaston, L. K.; Reed, S. K.; Shorey, H. H.','Bone L, Hammock B, Gaston L, Reed S, Shorey H. (1980). J. Chem. Ecol. 6:297–308','http://ucanr.org/sites/hammocklab/files/130967.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('041','Insect Biology','Regulation of juvenile hormone esterase in the cabbage looper, Trichoplusia ni',1981,'','','Regulation of Insect Development and Behavior','Hammock, B. D.; Jones, D.; Jones, G.; Rudnicka, M.; Sparks, T. C.; Wing, K. D.','Hammock B, Jones D, Jones G, Rudnicka  M, Sparks  T, Wing  K. (1981). In: Regulation of Insect Development and Behavior (Wroclaw Technical University Press, Wroclaw, Poland): 219–235','http://ucanr.org/sites/hammocklab/files/130973.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('042','Epoxide Hydrolase','Metabolism and environmental fate of juvenoids',1981,'','','Regulation of Insect Development and Behavior','Hammock, B. D.','Hammock B. (1981). In: Regulation of Insect Development and Behavior (Wroclaw Technical University Press, Wroclaw, Poland): 841–852','http://ucanr.org/sites/hammocklab/files/125211.pdf');
INSERT INTO biopest(bibnum,project,title,year,keyword,periodical,parent_title,author,citation,link) VALUES ('042','Insect Biology','Metabolism and environmental fate of juvenoids',1981,'','','Regulation of Insect Development and Behavior','Hammock, B. D.','Hammock B. (1981). In: Regulation of Insect Development and Behavior (Wroclaw Technical University Press, Wroclaw, Poland): 841–852','http://ucanr.org/sites/hammocklab/files/125211.pdf');
